base_dir: log/conv2d/
data:
  batch_size: 300
  dataset: data/conv2d_gsmap/all_data.npz
  test_batch_size: 1
  test_size: 0.2
  valid_size: 0.2
log_level: INFO
model:
  rnn_units: 200
  activation: relu
  seq_len: 4
  horizon: 0
train:
  dropout: 0
  epochs: 500
  optimizer: adam
  patience: 15
  loss: mse

