base_dir: log/ed_lstm/
data:
  batch_size: 300
  test_batch_size: 1
  test_size: 0.2
  valid_size: 0.2
log_level: INFO
model:
  rnn_units: 400
  activation: relu
  seq_len: 43
  horizon: 1
  input_dim: 3
  output_dim: 1
train:
  dropout: 0
  epochs: 500
  optimizer: adam
  patience: 25
  loss: mse